---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "helloworld-1"
  namespace: "default"
  labels:
    app: "helloworld-1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "helloworld-1"
  template:
    metadata:
      labels:
        app: "helloworld-1"
    spec:
      containers:
      - name: "cr-helloworld-1"
        image: "us.gcr.io/testproject1-344106/cr-helloworld:latest"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "helloworld-1-hpa-inor"
  namespace: "default"
  labels:
    app: "helloworld-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "helloworld-1"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

