apiVersion: "v1"
kind: "Service"
metadata:
  name: "helloworld-1-service"
  namespace: "default"
  labels:
    app: "helloworld-1"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "helloworld-1"
  type: "LoadBalancer"
  loadBalancerIP: ""
